seed_everything: 7
trainer:
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: '{epoch}-{step}-{val_ExpRate:.4f}'
  gpus: 1
#  gpus: 4
#  accelerator: ddp
  check_val_every_n_epoch: 2
  max_epochs: 300
model:
  d_model: 256
#  growth_rate: 24
#  num_layers: 16
  #4 -6.8M  8-6.9M 16-7.1M
  depths: [4,16,16,16]
    #   depths: [1, 1, 1, 1]
  dims: [ 36, 144, 264, 324, 528, 648, 708]
#  dims: [ 32, 128, 256, 320, 512, 640, 704]
#  dims: [ 48, 96, 120, 384, 192, 240, 768, 528]
#  dims: [ 48, 192,  240, 768, 528, 96, 120, 384]
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.3
  beam_size: 10
  max_len: 200
  alpha: 1.0
  learning_rate: 1.0
  patience: 20
data:
  zipfile_path: D:\data\data_+
  test_year: 2019
  batch_size: 8
  num_workers: 0
