alpha: 1.0
beam_size: 10
d_model: 256
depths:
- 4
- 16
- 16
- 16
dim_feedforward: 1024
dims:
- 36
- 144
- 264
- 324
- 528
- 648
- 708
dropout: 0.3
learning_rate: 1.0
max_len: 200
nhead: 8
num_decoder_layers: 3
patience: 20
